// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import * as Employee from "./Employee.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

import './styles/Employees.css'
;

function getImage(g) {
  if (g) {
    return "./images/femaleProfile.jpg";
  } else {
    return "./images/maleProfile.jpg";
  }
}

function Employees(props) {
  var setEmployeeList = props.setEmployeeList;
  var setSelectedTeam = props.setSelectedTeam;
  var selectedTeam = props.selectedTeam;
  var handleSelectedTeamChanged = function ($$event) {
    Curry._1(setSelectedTeam, $$event.target.value);
  };
  var handleEmployeeCardClick = function ($$event) {
    var clickedEmployeeId = Belt_Option.getExn(Belt_Int.fromString($$event.currentTarget.id));
    Curry._1(setEmployeeList, (function (e) {
            return Belt_Array.map(e, (function (e) {
                          if (e.id !== clickedEmployeeId || selectedTeam === "All Teams") {
                            return e;
                          } else if (e.teamName === selectedTeam) {
                            return {
                                    id: e.id,
                                    fullName: e.fullName,
                                    designation: e.designation,
                                    gender: e.gender,
                                    teamName: ""
                                  };
                          } else {
                            return {
                                    id: e.id,
                                    fullName: e.fullName,
                                    designation: e.designation,
                                    gender: e.gender,
                                    teamName: selectedTeam
                                  };
                          }
                        }));
          }));
  };
  var getSelectedEmployeeClassName = function (teamName) {
    if (teamName === selectedTeam) {
      return "card m-2 card-mouse-pointer standout";
    } else {
      return "card m-2 card-mouse-pointer";
    }
  };
  return React.createElement("main", {
              className: "container"
            }, React.createElement("div", {
                  className: "row justify-content-center mt-3 mb-3"
                }, React.createElement("div", {
                      className: "col-6"
                    }, React.createElement("select", {
                          className: "form-select form-select-lg",
                          value: selectedTeam,
                          onChange: handleSelectedTeamChanged
                        }, Belt_Array.map(Employee.getTeamNames(undefined), (function (t) {
                                return React.createElement("option", {
                                            key: t,
                                            value: t
                                          }, t);
                              }))))), React.createElement("div", {
                  className: "row justify-content-center mt-3 mb-3"
                }, React.createElement("div", {
                      className: "col-8"
                    }, React.createElement("div", {
                          className: "card-collection"
                        }, Belt_Array.map(props.employeeList, (function (e) {
                                return React.createElement("div", {
                                            key: String(e.id),
                                            className: getSelectedEmployeeClassName(e.teamName),
                                            id: String(e.id),
                                            onClick: handleEmployeeCardClick
                                          }, React.createElement("img", {
                                                className: "card-img-top",
                                                src: e.gender ? "./images/femaleProfile.jpg" : "./images/maleProfile.jpg"
                                              }), React.createElement("div", {
                                                className: "card-body"
                                              }, React.createElement("h5", {
                                                    className: "card-title"
                                                  }, e.fullName), React.createElement("p", {
                                                    className: "card-text"
                                                  }, React.createElement("b", undefined, "Designation:"), e.designation)));
                              }))))));
}

var make = Employees;

export {
  getImage ,
  make ,
}
/*  Not a pure module */
