// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_SortArray from "rescript/lib/es6/belt_SortArray.js";

var employeeList = [
  {
    id: 1,
    fullName: "Bob Jones",
    designation: "JavaScript Developer",
    gender: /* Male */0,
    teamName: "Team A"
  },
  {
    id: 2,
    fullName: "Jill Bailey",
    designation: "Node Developer",
    gender: /* Female */1,
    teamName: "Team A"
  },
  {
    id: 3,
    fullName: "Gail Shepherd",
    designation: "Java Developer",
    gender: /* Female */1,
    teamName: "Team A"
  },
  {
    id: 4,
    fullName: "Sam Reynolds",
    designation: "React Developer",
    gender: /* Male */0,
    teamName: "Team B"
  },
  {
    id: 5,
    fullName: "David Henry",
    designation: "DotNet Developer",
    gender: /* Male */0,
    teamName: "Team B"
  },
  {
    id: 6,
    fullName: "Sarah Blake",
    designation: "SQL Server DBA",
    gender: /* Female */1,
    teamName: "Team B"
  },
  {
    id: 7,
    fullName: "James Bennet",
    designation: "Angular Developer",
    gender: /* Male */0,
    teamName: "Team C"
  },
  {
    id: 8,
    fullName: "Jessica Faye",
    designation: "API Developer",
    gender: /* Female */1,
    teamName: "Team C"
  },
  {
    id: 9,
    fullName: "Lita Stone",
    designation: "C++ Developer",
    gender: /* Female */1,
    teamName: "Team C"
  },
  {
    id: 10,
    fullName: "Daniel Young",
    designation: "Python Developer",
    gender: /* Male */0,
    teamName: "Team D"
  },
  {
    id: 11,
    fullName: "Adrian Jacobs",
    designation: "Vue Developer",
    gender: /* Male */0,
    teamName: "Team D"
  },
  {
    id: 12,
    fullName: "Devin Monroe",
    designation: "Graphic Designer",
    gender: /* Male */0,
    teamName: "Team D"
  }
];

function getTeamNames(param) {
  return Belt_SortArray.stableSortBy(Belt_List.toArray(Belt_List.add(Belt_Array.reduce(Belt_Array.map(employeeList, (function (e) {
                                return e.teamName;
                              })), /* [] */0, (function (result, i) {
                            if (Belt_List.some(result, (function (x) {
                                      return x === i;
                                    }))) {
                              return result;
                            } else {
                              return Belt_List.add(result, i);
                            }
                          })), "All Teams")), (function (a, b) {
                if (a === b) {
                  return 0;
                } else if (a < b) {
                  return -1;
                } else {
                  return 1;
                }
              }));
}

export {
  employeeList ,
  getTeamNames ,
}
/* No side effect */
