// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Footer(props) {
  var date = new Date();
  return React.createElement("footer", {
              className: "container"
            }, React.createElement("div", {
                  className: "row justify-content-conter mt-3 mb-4"
                }, React.createElement("div", {
                      className: "col-8"
                    }, React.createElement("h5", undefined, "Team Allocation App - {" + String(date.getFullYear() | 0) + "}"))));
}

var make = Footer;

export {
  make ,
}
/* react Not a pure module */
