// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function GroupedTeamMembers(props) {
  return React.createElement("main", {
              className: "container"
            }, React.createElement("div", {
                  className: "row justify-content-center"
                }, React.createElement("div", {
                      className: "col-8"
                    }, React.createElement("h1", undefined, "Grouped Team Members"))));
}

var make = GroupedTeamMembers;

export {
  make ,
}
/* react Not a pure module */
