// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Js_array from "rescript/lib/es6/js_array.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function GroupedTeamMembers(props) {
  var setSelectedTeam = props.setSelectedTeam;
  var selectedTeam = props.selectedTeam;
  var employeeList = props.employeeList;
  var match = React.useState(function () {
        var mapping = {};
        Belt_Array.forEach(employeeList, (function (e) {
                var el = Js_dict.get(mapping, e.teamName);
                if (el !== undefined) {
                  Js_array.push(e, el);
                } else {
                  mapping[e.teamName] = [e];
                }
              }));
        return Belt_Array.map(Js_dict.entries(mapping), (function (param) {
                      var teamName = param[0];
                      return {
                              teamName: teamName,
                              teamMembers: param[1],
                              collapsed: teamName !== selectedTeam
                            };
                    }));
      });
  var setGroupedEmployees = match[1];
  var handleTeamClick = function ($$event) {
    var selectedTeam = $$event.target.id;
    Curry._1(setSelectedTeam, (function (param) {
            return selectedTeam;
          }));
    Curry._1(setGroupedEmployees, (function (geList) {
            return Belt_Array.map(geList, (function (param) {
                          var teamName = param.teamName;
                          return {
                                  teamName: teamName,
                                  teamMembers: param.teamMembers,
                                  collapsed: selectedTeam !== teamName
                                };
                        }));
          }));
  };
  return React.createElement("main", {
              className: "container"
            }, React.createElement("div", {
                  className: "row justify-content-center"
                }, Belt_Array.map(match[0], (function (ge) {
                        return React.createElement("div", {
                                    key: ge.teamName,
                                    className: "card mt-2",
                                    id: ge.teamName,
                                    style: {
                                      cursor: "pointer"
                                    }
                                  }, React.createElement("h4", {
                                        className: "card-header text-secondary bg-white",
                                        id: ge.teamName,
                                        onClick: handleTeamClick
                                      }, "Team Name " + ge.teamName + ""), React.createElement("div", {
                                        className: ge.collapsed ? "collapse" : "",
                                        id: "collapse_" + ge.teamName + ""
                                      }, React.createElement("hr", undefined), Belt_Array.map(ge.teamMembers, (function (e) {
                                              return React.createElement("div", {
                                                          key: e.fullName,
                                                          className: "mt-2",
                                                          id: e.fullName
                                                        }, React.createElement("h5", {
                                                              className: "card-title mt-2"
                                                            }, React.createElement("span", {
                                                                  className: "text-dark"
                                                                }, "Full Name " + e.fullName + "")), React.createElement("p", undefined, "Designation: " + e.designation + ""));
                                            }))));
                      }))));
}

var make = GroupedTeamMembers;

export {
  make ,
}
/* react Not a pure module */
