// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function Header(props) {
  var employeeList = props.employeeList;
  var selectedTeam = props.selectedTeam;
  return React.createElement("header", {
              className: "container"
            }, React.createElement("div", {
                  className: "row justify-content-center mt-3 mb-4"
                }, React.createElement("div", {
                      className: "col-8"
                    }, React.createElement("h1", {
                          className: "mt-4 p5 bg-warning text-white rounded"
                        }, selectedTeam === "All Teams" ? "" + selectedTeam + " Size: " + String(employeeList.length) + "" : "" + selectedTeam + " Size: " + String(Belt_Array.keep(employeeList, (function (e) {
                                      return e.teamName === selectedTeam;
                                    })).length) + "\n                "))));
}

var make = Header;

export {
  make ,
}
/* react Not a pure module */
