// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Main from "./Main.bs.js";
import * as React from "react";
import * as Client from "react-dom/client";

console.log("came inside the main application");

import ('bootstrap/dist/css/bootstrap.min.css')
;

var rootElement = document.querySelector("#main");

if (rootElement == null) {
  console.log("could not find main div");
} else {
  Client.createRoot(rootElement).render(React.createElement(Main.make, {}));
}

export {
  
}
/*  Not a pure module */
