// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as NavItem from "./NavItem.bs.js";

function Nav(props) {
  return React.createElement("nav", {
              className: "navbar navbar-expand-lg navbar-light bg-light"
            }, React.createElement("ul", {
                  className: "navbar-nav me-auto mb-2 ml-2 mr-2 mb-lg-0"
                }, React.createElement(NavItem.make, {
                      title: "Home",
                      linkTo: "/"
                    }), React.createElement(NavItem.make, {
                      title: "Teams",
                      linkTo: "/GroupedTeamMembers"
                    })));
}

var make = Nav;

export {
  make ,
}
/* react Not a pure module */
