// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

function NavItem(props) {
  var linkTo = props.linkTo;
  return React.createElement("li", {
              className: "nav-item",
              onClick: (function (param) {
                  RescriptReactRouter.push(linkTo);
                })
            }, props.title);
}

var make = NavItem;

export {
  make ,
}
/* react Not a pure module */
