// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function PageNotFound(props) {
  return React.createElement("div", undefined, React.createElement("p", undefined, "Page you are looking for does not exist"));
}

var make = PageNotFound;

export {
  make ,
}
/* react Not a pure module */
